import { test, expect } from "@playwright/test";
import { emptyMemory, type Workspace } from "../src/lib/workspace";
import JSZip from "jszip";

test("overview, navigation, search and responsive layout", async ({ page }) => {
  const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Active projects", exact: false })).toBeVisible();
  await page.screenshot({ path: "test-results/overview-desktop.png", fullPage: true });
  for (const name of ["Projects", "Tasks", "Memory", "AI Context", "Activity", "Settings", "Guide"]) {
    await page.locator(".sidebar nav").getByRole("button", { name, exact: false }).click();
    await expect(page.getByRole("heading", { name, exact: true, level: 1 })).toBeVisible();
  }
  await page.getByRole("button", { name: "Search anything..." }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.getByLabel("Search workspace").fill("this-project-does-not-exist-123");
  await expect(page.getByText("Nothing here yet. Try a different search.")).toBeVisible();
  await page.keyboard.press("Escape");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByLabel("Open navigation").click();
  await page.locator(".sidebar nav").getByRole("button", { name: "Overview", exact: true }).click();
  await page.screenshot({ path: "test-results/overview-mobile.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.getByRole("button", { name: "New project", exact: true }).first().click();
  await expect(page.getByRole("dialog")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.getByLabel("Close dialog").click();
  expect(errors).toEqual([]);
});

test.describe("Write tests — opt in only on a disposable workspace", () => {
  test.skip(process.env.PROJECT_OS_TEST_WRITE !== "1", "Set PROJECT_OS_TEST_WRITE=1 against a disposable test workspace to enable mutations.");
  let original: Workspace;
  test.beforeAll(async ({ request }) => { const response = await request.get("/api/workspace"); expect(response.ok()).toBeTruthy(); original = (await response.json()).data; });
  test.afterAll(async ({ request }) => {
    if (!original) return;
    const current = await (await request.get("/api/workspace")).json();
    const result = await request.put("/api/workspace", { data: { revision: current.revision, data: original, restore: true } });
    expect(result.ok()).toBeTruthy();
  });
  test("create, persist, complete, edit memory, build context and export", async ({ page, request }) => {
    const name = `QA project ${Date.now()}`;
    await page.goto("/"); await expect(page.getByRole("heading", { name: "Active projects", exact: false })).toBeVisible();
    await page.getByRole("button", { name: "New project", exact: true }).first().click();
    await page.getByLabel("Project name").fill(name);
    await page.getByLabel("Goal", { exact: true }).fill("Verify the complete local workflow");
    await page.getByLabel("Description", { exact: true }).fill("Temporary browser smoke test project");
    await page.getByRole("button", { name: "Create project", exact: true }).click();
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await page.reload();
    await page.locator(".sidebar nav").getByRole("button", { name: "Projects" }).click();
    await page.getByLabel("Search projects").fill(name);
    await page.getByRole("button", { name, exact: true }).click();
    await page.getByRole("button", { name: "View tasks" }).click();
    await page.getByRole("button", { name: "New task", exact: true }).click();
    await page.getByLabel("Task name").fill("Verify saved data survives a reload");
    await page.getByLabel("Completion criterion").fill("The task is still present after reloading the browser");
    await page.getByRole("button", { name: "Create task", exact: true }).click();
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await page.getByLabel("Complete Verify saved data survives a reload").click();
    await expect(page.getByRole("checkbox", { name: /I have checked the result/ })).not.toBeChecked();
    await page.getByRole("checkbox", { name: /I have checked the result/ }).check();
    await page.getByRole("button", { name: "Save changes", exact: true }).click();
    await expect(page.getByRole("dialog")).toHaveCount(0);
    const server = (await (await request.get("/api/workspace")).json()).data as Workspace;
    const project = server.projects.find(p => p.name === name)!;
    expect(server.tasks.find(t => t.projectId === project.id)?.status).toBe("DONE");
    await page.locator(".sidebar nav").getByRole("button", { name: "Memory", exact: true }).click();
    await page.getByLabel("Select project").selectOption(project.id);
    await page.getByRole("button", { name: "DECISIONS.md", exact: true }).click();
    await page.getByLabel("Edit DECISIONS.md").fill("# Decisions\n\nQA decision: keep one source of truth.");
    await expect(page.getByText("You have unsaved changes", { exact: true })).toBeVisible();
    await page.getByRole("button", { name: "Save changes", exact: true }).click();
    await expect(page.getByText("You have unsaved changes", { exact: true })).toHaveCount(0);
    await page.locator(".sidebar nav").getByRole("button", { name: "AI Context", exact: false }).click();
    await page.getByLabel("Select project").selectOption(project.id);
    await page.getByLabel("What would you like to work on?").fill("Suggest the smallest useful next step.");
    await expect(page.locator(".context-preview pre")).toContainText("QA decision: keep one source of truth.");
    await expect(page.locator(".context-preview pre")).toContainText("[x] Verify saved data survives a reload");
    await expect(page.getByRole("link", { name: "Open ChatGPT" })).toHaveAttribute("href", "https://chatgpt.com");
    await page.context().grantPermissions(["clipboard-read", "clipboard-write"]);
    await page.getByRole("button", { name: "Copy context", exact: true }).click();
    await expect(page.getByRole("button", { name: "Copied!", exact: true })).toBeVisible();
    expect(await page.evaluate(() => navigator.clipboard.readText())).toContain("QA decision: keep one source of truth.");
    await page.locator(".sidebar nav").getByRole("button", { name: "Settings", exact: true }).click();
    const jsonPromise = page.waitForEvent("download"); await page.getByRole("button", { name: "Export JSON", exact: true }).click();
    const jsonDownload = await jsonPromise; const jsonStream = await jsonDownload.createReadStream(); const chunks = [];
    for await (const chunk of jsonStream!) chunks.push(chunk);
    const backup = JSON.parse(Buffer.concat(chunks).toString("utf8")) as Workspace;
    expect(backup.projects.some(p => p.name === name)).toBeTruthy();
    const zipPromise = page.waitForEvent("download"); await page.getByRole("button", { name: "Export ZIP + Markdown", exact: true }).click();
    const zipDownload = await zipPromise; const zipStream = await zipDownload.createReadStream(); const zipChunks = [];
    for await (const chunk of zipStream!) zipChunks.push(chunk);
    const zip = await JSZip.loadAsync(Buffer.concat(zipChunks));
    expect(zip.file("workspace.json")).not.toBeNull();
    expect(Object.keys(zip.files).filter(f => f.endsWith("TASKS.md")).length).toBe(backup.projects.length);
  });
  test("API rejects invalid states and stale revisions without losing data", async ({ request }) => {
    const current = await (await request.get("/api/workspace")).json() as { data: Workspace; revision: number };
    const p = { id: crypto.randomUUID(), name: "Validation fixture", description: "", goal: "", category: "Development", color: "teal" as const, status: "Active" as const, stage: "Testing", createdAt: new Date().toISOString(), memory: emptyMemory("Validation fixture") };
    const fixture = { ...current.data, projects: [...current.data.projects, p] };
    const task = { id: crypto.randomUUID(), projectId: p.id, title: "Invalid DONE", description: "", priority: "High" as const, status: "DONE" as const, criterion: "", confirmed: false, dependencies: [], createdAt: new Date().toISOString() };
    const invalidDone = await request.put("/api/workspace", { data: { revision: current.revision, data: { ...fixture, tasks: [...fixture.tasks, task] } } });
    expect(invalidDone.status()).toBe(400);
    const invalidId = await request.put("/api/workspace", { data: { revision: current.revision, data: { ...fixture, tasks: [...fixture.tasks, { ...task, status: "READY", projectId: crypto.randomUUID() }] } } });
    expect(invalidId.status()).toBe(400);
    const t1 = { ...task, status: "READY", dependencies: [crypto.randomUUID()] }; const t2 = { ...t1, id: t1.dependencies[0], dependencies: [t1.id] };
    const cyclic = await request.put("/api/workspace", { data: { revision: current.revision, data: { ...fixture, tasks: [...fixture.tasks, t1, t2] } } });
    expect(cyclic.status()).toBe(400);
    const crossOrigin = await request.put("/api/workspace", { headers: { origin: "https://untrusted.example" }, data: { revision: current.revision, data: current.data } });
    expect(crossOrigin.status()).toBe(403);
    const valid = await request.put("/api/workspace", { data: { revision: current.revision, data: { ...current.data, name: "QA concurrency check" } } });
    expect(valid.ok()).toBeTruthy();
    const conflict = await request.put("/api/workspace", { data: { revision: current.revision, data: current.data } });
    expect(conflict.status()).toBe(409);
    const latest = await (await request.get("/api/workspace")).json();
    expect(latest.data.name).toBe("QA concurrency check");
    expect(latest.data.tasks).toEqual(current.data.tasks);
  });
  test("JSON restoration creates a recoverable pre-restore snapshot", async ({ page, request }) => {
    const current = await (await request.get("/api/workspace")).json();
    const incoming = { ...current.data, name: "QA restored workspace" };
    await page.goto("/"); await expect(page.getByRole("heading", { name: "Active projects", exact: false })).toBeVisible();
    await page.locator(".sidebar nav").getByRole("button", { name: "Settings", exact: true }).click();
    page.once("dialog", dialog => dialog.accept());
    const response = page.waitForResponse(res => res.url().endsWith("/api/workspace") && res.request().method() === "PUT");
    await page.locator('input[type="file"]').setInputFiles({ name: "workspace.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(incoming)) });
    expect((await response).ok()).toBeTruthy();
    await expect(page.getByLabel("Workspace name")).toHaveValue("QA restored workspace");
    const previous = await (await request.get("/api/backups")).json();
    expect(previous).toEqual(current.data);
    await page.reload();
    const persisted = await (await request.get("/api/workspace")).json();
    expect(persisted.data.name).toBe("QA restored workspace");
  });
});
