"use client";
import { useCallback, useEffect, useRef, useState, type ElementType } from "react";
import { LayoutDashboard, FolderKanban, ListTodo, BookOpen, Sparkles, Activity as ActivityIcon, Settings2, CircleHelp, Search, Bell, ChevronRight, ChevronDown, Plus, ArrowRight, ArrowUpRight, FolderOpen, CircleCheck, Circle, Clock3, Ellipsis, Check, X, CalendarDays, SlidersHorizontal, ShieldCheck, HardDrive, PanelLeftClose, Menu, AlertCircle, Loader2, FileText, CheckCheck, Code2, Globe, Library, Compass, Command, Download, Archive, ExternalLink, ListFilter, WifiOff } from "lucide-react";
import { type Workspace, type Project, type Task, type Activity, statuses } from "@/lib/workspace";
import { Modal, ProjectForm, TaskForm } from "./editors";
import { ContextPanel, MemoryPanel, SettingsPanel, GuidePanel, download } from "./workspace-panels";

type View = "Overview" | "Projects" | "Tasks" | "Memory" | "AI Context" | "Activity" | "Settings" | "Guide";
const nav: { name: View; icon: ElementType }[] = [{ name: "Overview", icon: LayoutDashboard }, { name: "Projects", icon: FolderKanban }, { name: "Tasks", icon: ListTodo }, { name: "Memory", icon: BookOpen }, { name: "AI Context", icon: Sparkles }];
const systemNav: { name: View; icon: ElementType }[] = [{ name: "Activity", icon: ActivityIcon }, { name: "Settings", icon: Settings2 }, { name: "Guide", icon: CircleHelp }];
const descriptions: Record<View, string> = { Overview: "Everything you’re building, in one place.", Projects: "Big ideas, clear goals, and the space to move them forward.", Tasks: "A little progress, one useful step at a time.", Memory: "Keep the decisions, details, and context that matter.", "AI Context": "Pick up where you left off. Bring your AI up to speed.", Activity: "A living record of the progress you’re making.", Settings: "Your workspace, your data, your way.", Guide: "Less time figuring things out. More time moving forward." };
function statusClass(s: string) { return s.toLowerCase().replaceAll(" ", "-"); }
function relativeTime(value: string) { const min = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000)); return min < 1 ? "Just now" : min < 60 ? `${min}m ago` : min < 1440 ? `${Math.floor(min / 60)}h ago` : `${Math.floor(min / 1440)}d ago`; }
function ProjectIcon({ p, size = 21 }: { p: Project; size?: number }) { const Icon = p.category === "Development" ? Code2 : p.category === "Design" ? Globe : p.category === "Learning" ? Compass : Library; return <span className={`project-icon ${p.color}`}><Icon size={size}/></span>; }
function StatusBadge({ status }: { status: string }) { return <span className={`status-badge ${statusClass(status)}`}><span/>{status === "IN PROGRESS" ? "In progress" : status.charAt(0) + status.slice(1).toLowerCase()}</span>; }
function ActivityList({ items, onProject, full = false }: { items: Activity[]; onProject: (id: string | null) => void; full?: boolean }) {
  return <div className={`activity-list ${full ? "full-activity" : ""}`}>{items.length ? items.map(a => { const Icon = a.type === "memory" ? FileText : a.type === "task" ? CheckCheck : a.type === "project" ? FolderOpen : Sparkles; return <div className="activity-item" key={a.id}><span className={`activity-symbol ${a.type}`}><Icon size={15}/></span><div><button className="activity-title" onClick={() => onProject(a.projectId)}>{a.title}</button><p>{a.detail}</p>{!full && <small>{relativeTime(a.createdAt)}</small>}</div>{full && <time dateTime={a.createdAt}>{new Date(a.createdAt).toLocaleString("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })}</time>}</div>; }) : <div className="small-empty">Your next step starts the story. Changes will appear here.</div>}</div>;
}
export default function WorkspaceApp() {
  const [w, setW] = useState<Workspace | null>(null); const [revision, setRevision] = useState(0);
  const [view, setView] = useState<View>("Overview"); const [loadError, setLoadError] = useState(""); const [busy, setBusy] = useState(false); const saving = useRef(false);
  const [toast, setToast] = useState<{ message: string; error: boolean } | null>(null); const toastTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [projectModal, setProjectModal] = useState<Project | "new" | null>(null); const [taskModal, setTaskModal] = useState<Task | "new" | null>(null);
  const [mobileNav, setMobileNav] = useState(false); const [projectMenu, setProjectMenu] = useState<string | null>(null);
  const [projectFilter, setProjectFilter] = useState("All projects"); const [taskFilter, setTaskFilter] = useState("Open"); const [taskProject, setTaskProject] = useState("all"); const [priorityFilter, setPriorityFilter] = useState("All priorities"); const [showFilters, setShowFilters] = useState(false);
  const [projectQuery, setProjectQuery] = useState(""); const [taskQuery, setTaskQuery] = useState(""); const [initialProject, setInitialProject] = useState("");
  const [searchOpen, setSearchOpen] = useState(false); const [search, setSearch] = useState(""); const [notifications, setNotifications] = useState(false); const [dirty, setDirty] = useState(false);
  const [activityFilter, setActivityFilter] = useState("All activity");
  const notify = useCallback((message: string, error = false) => { if (toastTimer.current) clearTimeout(toastTimer.current); setToast({ message, error }); toastTimer.current = setTimeout(() => setToast(null), error ? 11000 : 4000); }, []);
  const load = useCallback((signal?: AbortSignal) => {
    return fetch("/api/workspace", { cache: "no-store", signal })
      .then(async response => { const result = await response.json(); if (!response.ok) throw new Error(result.error); return result as { data: Workspace; revision: number }; })
      .then(result => { setW(result.data); setRevision(result.revision); setLoadError(""); })
      .catch((error: unknown) => { if (error instanceof Error && error.name === "AbortError") return; setLoadError(error instanceof Error ? error.message : "Could not reach your workspace."); });
  }, []);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  useEffect(() => { const key = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key === "k") { e.preventDefault(); setSearchOpen(v => !v); } }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, []);
  const go = (next: View) => { if (next === view) { setMobileNav(false); return; } if (dirty && !window.confirm("Discard unsaved memory changes?")) return; setView(next); setMobileNav(false); setProjectMenu(null); setNotifications(false); setDirty(false); };
  const save = async (data: Workspace, message = "Changes saved", restore = false): Promise<boolean> => {
    if (saving.current) return false; saving.current = true; setBusy(true);
    try { const res = await fetch("/api/workspace", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ data, revision, restore }) }); const result = await res.json(); if (!res.ok) throw new Error(result.error); setW(result.data); setRevision(result.revision); notify(message); return true; } catch (e) { notify(e instanceof Error ? e.message : "Could not save. Please try again.", true); return false; } finally { setBusy(false); saving.current = false; }
  };
  const toProjectArea = (id: string, area: View) => { if (dirty && !window.confirm("Discard unsaved memory changes?")) return; setDirty(false); setInitialProject(id); if (area === "Tasks") { setTaskProject(id); setTaskFilter("Open"); } setProjectModal(null); setProjectMenu(null); setNotifications(false); setMobileNav(false); setView(area); };
  const closeModal = () => { if (saving.current) return; setProjectModal(null); setTaskModal(null); };
  const openProject = (id: string | null) => { const p = w?.projects.find(p => p.id === id); if (p) setProjectModal(p); else go("Activity"); };
  const archive = async (p: Project) => { if (!w || !window.confirm(`Archive “${p.name}”? Its tasks and memory will be kept.`)) return; if (await save({ ...w, projects: w.projects.map(x => x.id === p.id ? { ...x, status: "Archived" } : x) }, "Project archived")) closeModal(); setProjectMenu(null); };
  const newTask = () => { if (!w?.projects.length) { notify("Create a project first, then add your first task."); setProjectModal("new"); } else setTaskModal("new"); };
  const active = w?.projects.filter(p => p.status === "Active") ?? [];
  const openTasks = w?.tasks.filter(t => !["DONE", "CANCELLED"].includes(t.status) && w.projects.find(p => p.id === t.projectId)?.status !== "Archived") ?? [];
  const inProgress = openTasks.filter(t => t.status === "IN PROGRESS");
  const attention = openTasks.filter(t => t.status === "BLOCKED" || t.status === "REVIEW");
  const completed = w?.tasks.filter(t => t.status === "DONE") ?? [];
  const filteredTasks = (w?.tasks ?? []).filter(t => {
    const p = w?.projects.find(p => p.id === t.projectId);
    return (taskProject === "all" ? p?.status !== "Archived" : t.projectId === taskProject) && (taskFilter === "All" || (taskFilter === "Open" ? !["DONE", "CANCELLED"].includes(t.status) : taskFilter === "Completed" ? t.status === "DONE" : taskFilter === "In progress" ? t.status === "IN PROGRESS" : taskFilter === "Needs attention" ? ["BLOCKED", "REVIEW"].includes(t.status) : t.status === taskFilter)) && (priorityFilter === "All priorities" || t.priority === priorityFilter) && `${t.title} ${p?.name}`.toLowerCase().includes(taskQuery.toLowerCase());
  });
  const projectCards = (projects: Project[]) => projects.length ? <div className="project-grid">{projects.map(p => {
    const tasks = w!.tasks.filter(t => t.projectId === p.id && t.status !== "CANCELLED"); const done = tasks.filter(t => t.status === "DONE").length; const progress = tasks.length ? Math.round(done / tasks.length * 100) : 0;
    return <article key={p.id} className={`project-card accent-${p.color}`}><div className="project-card-top"><ProjectIcon p={p}/><StatusBadge status={p.status}/><div className="card-menu-wrap"><button className="icon-button" aria-label={`Actions for ${p.name}`} aria-expanded={projectMenu === p.id} onClick={() => setProjectMenu(projectMenu === p.id ? null : p.id)}><Ellipsis size={19}/></button>{projectMenu === p.id && <><button className="menu-dismiss" aria-label="Close project actions" onClick={() => setProjectMenu(null)}/><div className="dropdown card-dropdown"><button onClick={() => { setProjectModal(p); setProjectMenu(null); }}><SlidersHorizontal size={14}/> Edit project</button><button onClick={() => toProjectArea(p.id, "Memory")}><BookOpen size={14}/> Open memory</button><button onClick={() => toProjectArea(p.id, "AI Context")}><Sparkles size={14}/> Build AI context</button>{p.status !== "Archived" && <button onClick={() => archive(p)} disabled={busy}><Archive size={14}/> Archive project</button>}</div></>}</div></div><button className="project-card-title" onClick={() => setProjectModal(p)}>{p.name}<ArrowUpRight size={17}/></button><p className="project-description">{p.description || "A new idea, ready to take shape."}</p><div className="project-labels"><span>{p.category || "Personal"}</span><span className="stage-label"><i/>{p.stage || "Planning"}</span></div><div className="progress-heading"><span>Progress</span><span>{progress}%</span></div><div className="progress-track"><span style={{ width: `${progress}%` }}/></div><div className="project-card-footer"><button onClick={() => toProjectArea(p.id, "Tasks")}><ListTodo size={14}/>{done}/{tasks.length} tasks</button><button onClick={() => toProjectArea(p.id, "Memory")}><FileText size={13}/> {memoryFilesCount} files</button><span className="project-initial">{p.name.split(" ").map(s => s[0]).slice(0, 2).join("")}</span></div></article>;
  })}</div> : <div className="empty-state panel"><FolderOpen size={32}/><h3>A little space for your next big thing.</h3><p>{projectQuery ? "No projects match your search. Try a different name." : "Create a project and give your idea a place to grow."}</p><button className="button primary" onClick={() => setProjectModal("new")}><Plus size={16}/> New project</button></div>;
  const taskTable = (tasks: Task[], dashboard = false) => <div className="task-table-wrap"><table className="task-table"><thead><tr><th className="task-check-cell"/><th>Task</th><th>Status</th><th>Priority</th>{!dashboard && <th>Created</th>}<th className="task-more-cell"/></tr></thead><tbody>{tasks.map(t => { const p = w!.projects.find(p => p.id === t.projectId)!; return <tr key={t.id}><td className="task-check-cell"><button className={`task-check ${t.status === "DONE" ? "checked" : ""}`} aria-label={t.status === "DONE" ? `Review ${t.title}` : `Complete ${t.title}`} onClick={() => setTaskModal({ ...t, status: "DONE", confirmed: t.status === "DONE" && t.confirmed })}>{t.status === "DONE" && <Check size={11}/>}</button></td><td><button className={`task-title ${t.status === "DONE" ? "task-done" : ""}`} onClick={() => setTaskModal(t)}>{t.title}</button><span className="task-project"><i className={`color-dot ${p.color}`}/>{p.name}</span></td><td><StatusBadge status={t.status}/></td><td><span className={`priority ${t.priority.toLowerCase()}`}><span className="priority-bars"><i/><i/><i/></span>{t.priority}</span></td>{!dashboard && <td className="muted">{new Date(t.createdAt).toLocaleDateString("en-US", { month: "short", day: "numeric" })}</td>}<td><button className="icon-button row-more" aria-label={`Edit ${t.title}`} onClick={() => setTaskModal(t)}><Ellipsis size={17}/></button></td></tr>; })}</tbody></table>{!tasks.length && <div className="small-empty"><CircleCheck size={24}/><h3>All clear here.</h3><p>No tasks match this view. Add a task or adjust your filters.</p><button className="text-button" onClick={newTask}><Plus size={14}/> Add a task</button></div>}</div>;
  const taskTabs = (dashboard = false) => <div className="task-tabs">{["Open", "In progress", "Completed"].map(tab => <button key={tab} className={taskFilter === tab ? "active" : ""} onClick={() => setTaskFilter(tab)}>{tab === "Open" ? "Upcoming" : tab}<span>{tab === "Open" ? openTasks.length : tab === "In progress" ? inProgress.length : completed.length}</span></button>)}{!dashboard && <button className={!["Open", "In progress", "Completed"].includes(taskFilter) ? "active" : ""} onClick={() => { setTaskFilter("All"); setShowFilters(true); }}>All tasks</button>}<div className="action-spacer"/><button className="filter-icon" aria-label="Filter tasks" onClick={() => { if (dashboard) go("Tasks"); setShowFilters(v => !v); }}><ListFilter size={17}/></button></div>;
  return <div className="app-shell"><aside className={`sidebar ${mobileNav ? "mobile-open" : ""}`}><a href="#" className="brand" onClick={e => { e.preventDefault(); go("Overview"); }}><span className="brand-mark"><i/><i/><i/><i/></span><span>Project<span className="brand-os">OS</span></span><span className="version-badge">v2</span></a><button className="workspace-switch" onClick={() => go("Settings")}><span className="workspace-avatar"><FolderOpen size={17}/></span><span><b>{w?.name ?? "My workspace"}</b><small>Personal workspace</small></span><ChevronDown size={15}/></button><div className="nav-section-label">WORKSPACE</div><nav aria-label="Main navigation">{nav.map(item => <button key={item.name} className={`nav-item ${view === item.name ? "active" : ""}`} onClick={() => go(item.name)}><item.icon size={19}/><span>{item.name}</span>{item.name === "Projects" && <span className="nav-count">{w?.projects.filter(p => p.status !== "Archived").length ?? 0}</span>}{item.name === "AI Context" && <span className="nav-spark">✧</span>}</button>)}</nav><div className="nav-section-label system-label">SYSTEM</div><nav aria-label="System navigation">{systemNav.map(item => <button key={item.name} className={`nav-item ${view === item.name ? "active" : ""}`} onClick={() => go(item.name)}><item.icon size={18}/><span>{item.name}</span>{item.name === "Guide" && <ArrowUpRight size={13} className="guide-arrow"/>}</button>)}</nav><div className="sidebar-bottom"><div className="local-card"><span className="local-card-icon"><ShieldCheck size={19}/></span><h4>Your work. Your machine.</h4><p>Local-first. Private by design.<br/>Always in your hands.</p><span className="local-indicator"><i/> Local workspace</span></div><button className="sidebar-export" onClick={() => { if (w) { download(JSON.stringify(w, null, 2), `project-os-${new Date().toISOString().slice(0, 10)}.json`); notify("Workspace backup downloaded"); } }} disabled={!w}><Download size={16}/><span>Export workspace</span><ArrowUpRight size={13}/></button><div className="sidebar-footer"><span>Made for meaningful progress.</span><button aria-label="Close sidebar" className="icon-button" onClick={() => setMobileNav(false)}><PanelLeftClose size={14}/></button></div></div></aside>{mobileNav && <button className="sidebar-backdrop" aria-label="Close navigation" onClick={() => setMobileNav(false)}/>}
  <div className="main-shell"><header className="topbar"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={() => setMobileNav(true)}><Menu size={21}/></button><div className="breadcrumb"><span>{w?.name ?? "My workspace"}</span><ChevronRight size={13}/><strong>{view}</strong></div><div className="topbar-actions"><button className="search-trigger" onClick={() => { setSearchOpen(true); setSearch(""); }}><Search size={15}/><span>Search anything...</span><kbd>⌘ K</kbd></button><span className="topbar-divider"/><span className="saved-indicator">{busy ? <Loader2 size={14} className="spin"/> : <i/>}{busy ? "Saving…" : dirty ? "Unsaved changes" : w ? "All changes saved" : "Connecting…"}</span><div className="notification-wrap"><button className="icon-button notification-button" aria-label="Notifications" aria-expanded={notifications} onClick={() => setNotifications(!notifications)}><Bell size={18}/>{attention.length > 0 && <i/>}</button>{notifications && <div className="dropdown notifications"><h3>Needs a little attention <span>{attention.length}</span></h3>{attention.length ? attention.map(t => <button key={t.id} onClick={() => { setTaskModal(t); setNotifications(false); }}><AlertCircle size={17}/><span>{t.title}<small>{t.status === "BLOCKED" ? "Blocked · Find a way forward" : "In review · Check the result"}</small></span><ChevronRight size={14}/></button>) : <p className="small-empty">You’re all caught up.</p>}<button className="notification-footer" onClick={() => go("Activity")}>View workspace activity <ArrowRight size={14}/></button></div>}</div><button className="user-avatar" aria-label="Workspace settings" onClick={() => go("Settings")}>ME</button></div></header>
  <main className="main-content"><div className="page-intro"><div><div className="page-eyebrow">{view === "Overview" ? <><span className="greeting-dot"/> A LITTLE CLARITY FOR YOUR NEXT BIG THING</> : "YOUR PERSONAL PROJECT OPERATING SYSTEM"}</div><h1>{view}</h1><p>{descriptions[view]}</p></div><div className="page-actions">{view === "Overview" && <button className="button" onClick={() => go("AI Context")}><Sparkles size={16}/> Build AI context</button>}{["Overview", "Projects"].includes(view) && <button className="button primary" onClick={() => setProjectModal("new")} disabled={!w}><Plus size={17}/> New project</button>}{view === "Tasks" && <button className="button primary" onClick={newTask} disabled={!w}><Plus size={17}/> New task</button>}{["Memory", "Activity"].includes(view) && <span className="date-label"><CalendarDays size={15}/>{new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}</span>}</div></div>
  {!w ? (loadError ? <div className="panel error-state"><WifiOff size={32}/><h2>Let’s reconnect your workspace.</h2><p>{loadError}</p><button className="button primary" onClick={() => { setLoadError(""); void load(); }}>Try again</button><small>Your existing data has not been changed.</small></div> : <div className="loading-state"><div className="skeleton-stats">{[1, 2, 3, 4].map(i => <div key={i} className="skeleton"/>)}</div><div className="skeleton large"/><span><Loader2 size={16} className="spin"/> Opening your workspace…</span></div>) : <>
  {view === "Overview" && <><div className="overview-date"><CalendarDays size={14}/>{new Date().toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" })}<span className="date-line"/><span>Make a little room for progress.</span></div><div className="stats-grid">{[
    { label: "Active projects", value: active.length, icon: FolderKanban, cls: "teal", footer: `${w.projects.filter(p => p.status === "On hold").length} on hold`, hint: "Across your workspace", click: () => { setProjectFilter("Active"); go("Projects"); } },
    { label: "Open tasks", value: openTasks.length, icon: ListTodo, cls: "blue", footer: `${completed.length} completed`, hint: "One step at a time", click: () => { setTaskFilter("Open"); setTaskProject("all"); go("Tasks"); } },
    { label: "In progress", value: inProgress.length, icon: Clock3, cls: "purple", footer: "Keep the momentum", hint: "Where your focus is", click: () => { setTaskFilter("In progress"); setTaskProject("all"); go("Tasks"); } },
    { label: "Needs attention", value: attention.length, icon: AlertCircle, cls: "orange", footer: `${attention.filter(t => t.status === "BLOCKED").length} blocked · ${attention.filter(t => t.status === "REVIEW").length} in review`, hint: "A little nudge forward", click: () => { setTaskFilter("Needs attention"); setTaskProject("all"); go("Tasks"); } },
  ].map(s => <button key={s.label} className="stat-card" onClick={s.click}><div className="stat-top"><span>{s.label}</span><span className={`stat-icon ${s.cls}`}><s.icon size={18}/></span></div><div className="stat-value">{s.value}<span>{s.hint}</span></div><div className={`stat-footer ${s.cls}`}>{s.label === "Open tasks" ? <CircleCheck size={12}/> : s.label === "In progress" ? <span className="tiny-dot"/> : null}{s.footer}<ArrowUpRight size={13}/></div></button>)}</div>
  <section className="projects-section"><div className="section-heading"><h2>Active projects <span className="heading-count">{active.length}</span></h2><button className="text-button" onClick={() => { setProjectFilter("All projects"); go("Projects"); }}>View all projects <ArrowRight size={15}/></button></div>{projectCards(active.slice(0, 3))}</section>
  <div className="overview-bottom"><section className="panel focus-panel"><div className="section-heading panel-heading"><h2>Your next steps</h2><button className="text-button" onClick={() => { setTaskProject("all"); go("Tasks"); }}>All tasks <ArrowRight size={14}/></button></div>{taskTabs(true)}{taskTable((taskFilter === "Completed" ? completed : taskFilter === "In progress" ? inProgress : openTasks).slice(0, 5), true)}<button className="add-task-row" onClick={newTask}><Plus size={16}/> Add a task<span>Small steps add up.</span></button></section><div className="overview-right"><section className="panel recent-panel"><div className="section-heading panel-heading"><h2>Recent activity</h2><button className="icon-button" aria-label="View all activity" onClick={() => go("Activity")}><ArrowUpRight size={16}/></button></div><ActivityList items={w.activity.slice(0, 3)} onProject={openProject}/><button className="activity-view-all" onClick={() => go("Activity")}>View all activity <ArrowRight size={13}/></button></section><section className="ai-callout"><div className="ai-callout-art"><Sparkles size={21}/><span className="orb orb-one"/><span className="orb orb-two"/><span className="art-star">✧</span></div><span className="mini-eyebrow">PICK UP WHERE YOU LEFT OFF</span><h3>Your context. Ready for AI.</h3><p>Bring your projects, decisions, and next<br className="desktop-break"/> steps into your next conversation.</p><button onClick={() => go("AI Context")}>Build AI context <ArrowUpRight size={15}/></button><div className="ai-callout-note"><ShieldCheck size={11}/> No API key needed</div></section></div></div></>}
  {view === "Projects" && <><div className="view-toolbar"><div className="segmented-tabs">{["All projects", "Active", "On hold", "Completed", "Archived"].map(f => <button key={f} className={projectFilter === f ? "active" : ""} onClick={() => setProjectFilter(f)}>{f}{f === "All projects" && <span>{w.projects.filter(p => p.status !== "Archived").length}</span>}</button>)}</div><div className="inline-search"><Search size={15}/><input aria-label="Search projects" value={projectQuery} onChange={e => setProjectQuery(e.target.value)} placeholder="Find a project…"/></div></div>{projectCards(w.projects.filter(p => (projectFilter === "All projects" ? p.status !== "Archived" : p.status === projectFilter) && `${p.name} ${p.description} ${p.category}`.toLowerCase().includes(projectQuery.toLowerCase())))}</>}
  {view === "Tasks" && <><div className="view-toolbar"><div className="project-select"><FolderOpen size={16}/><select aria-label="Filter by project" value={taskProject} onChange={e => setTaskProject(e.target.value)}><option value="all">All active projects</option>{w.projects.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select></div><div className="toolbar-right"><div className="inline-search"><Search size={15}/><input placeholder="Find a task…" aria-label="Search tasks" value={taskQuery} onChange={e => setTaskQuery(e.target.value)}/></div><button className={`button ${showFilters ? "selected" : ""}`} onClick={() => setShowFilters(!showFilters)}><SlidersHorizontal size={15}/> Filters</button></div></div>{showFilters && <div className="filter-bar"><label>Status<select value={taskFilter} onChange={e => setTaskFilter(e.target.value)}><option>All</option><option>Open</option><option>In progress</option><option>Completed</option><option>Needs attention</option>{statuses.map(s => <option key={s}>{s}</option>)}</select></label><label>Priority<select value={priorityFilter} onChange={e => setPriorityFilter(e.target.value)}>{["All priorities", "High", "Medium", "Low"].map(s => <option key={s}>{s}</option>)}</select></label><button className="text-button" onClick={() => { setTaskFilter("Open"); setPriorityFilter("All priorities"); setTaskQuery(""); setTaskProject("all"); }}>Reset filters</button></div>}<section className="panel all-tasks-panel">{taskTabs()}{taskTable(filteredTasks)}<button className="add-task-row" onClick={newTask}><Plus size={16}/> Add a task<span>{filteredTasks.length} tasks in this view</span></button></section><div className="task-bottom-note"><ShieldCheck size={14}/> Done means done. Every completed task has a checked completion criterion.</div></>}
  {view === "Memory" && <MemoryPanel key={`memory-${initialProject}`} w={w} initialProject={initialProject} save={save} busy={busy} notify={notify} onDirty={setDirty}/>}
  {view === "AI Context" && <ContextPanel key={`context-${initialProject}`} w={w} initialProject={initialProject} notify={notify}/>}
  {view === "Activity" && <><div className="view-toolbar"><div className="segmented-tabs">{["All activity", "Projects", "Tasks", "Memory", "System"].map(f => <button key={f} className={activityFilter === f ? "active" : ""} onClick={() => setActivityFilter(f)}>{f}</button>)}</div><span className="quiet-note"><ActivityIcon size={14}/> {w.activity.length} recorded changes</span></div><section className="panel"><div className="panel-heading section-heading"><h2>Your workspace story</h2><span className="quiet-note">Newest first</span></div><ActivityList full items={w.activity.filter(a => activityFilter === "All activity" || a.type === ({ Projects: "project", Tasks: "task", Memory: "memory", System: "system" } as Record<string, string>)[activityFilter])} onProject={openProject}/></section></>}
  {view === "Settings" && <SettingsPanel w={w} save={save} busy={busy} notify={notify}/>}
  {view === "Guide" && <GuidePanel notify={notify}/>}
  <footer className="content-footer"><span><HardDrive size={13}/>{w.sample ? "Example workspace" : "Your data stays with you"}<i/>Stored in PostgreSQL</span><span>Think clearly. Build intentionally.<span className="footer-spark">✧</span></span></footer></>}
  </main></div>
  {projectModal && w && <ProjectForm key={projectModal === "new" ? "new-project" : projectModal.id} project={projectModal === "new" ? undefined : projectModal} busy={busy} onClose={closeModal} onSave={async p => { if (await save({ ...w, projects: projectModal === "new" ? [...w.projects, p] : w.projects.map(x => x.id === p.id ? p : x) }, projectModal === "new" ? "Your new project is ready" : "Project updated")) closeModal(); }} onArchive={projectModal === "new" ? undefined : () => archive(projectModal)} onTasks={projectModal === "new" ? undefined : () => toProjectArea(projectModal.id, "Tasks")} onMemory={projectModal === "new" ? undefined : () => toProjectArea(projectModal.id, "Memory")}/>}
  {taskModal && w && <TaskForm key={taskModal === "new" ? "new-task" : taskModal.id} task={taskModal === "new" ? undefined : taskModal} projects={w.projects} tasks={w.tasks} projectId={taskProject === "all" ? undefined : taskProject} busy={busy} onClose={closeModal} onSave={async t => { if (await save({ ...w, tasks: taskModal === "new" ? [...w.tasks, t] : w.tasks.map(x => x.id === t.id ? t : x) }, taskModal === "new" ? "Task added. One step closer." : "Task updated")) closeModal(); }} onDelete={() => { if (taskModal !== "new" && window.confirm(`Delete “${taskModal.title}”? This cannot be undone without restoring a backup.`)) void save({ ...w, tasks: w.tasks.filter(t => t.id !== taskModal.id) }, "Task deleted").then(ok => { if (ok) closeModal(); }); }}/>}
  {searchOpen && <Modal title="Find your next step" subtitle="Search projects and tasks across your workspace." onClose={() => setSearchOpen(false)}><div className="global-search-input"><Search size={20}/><input autoFocus aria-label="Search workspace" placeholder="Search anything…" value={search} onChange={e => setSearch(e.target.value)}/><kbd>ESC</kbd></div><div className="global-search-results"><div className="eyebrow">PROJECTS</div>{w?.projects.filter(p => p.name.toLowerCase().includes(search.toLowerCase())).slice(0, 5).map(p => <button key={p.id} onClick={() => { setSearchOpen(false); setProjectModal(p); }}><ProjectIcon p={p} size={17}/><span>{p.name}<small>{p.category} · {p.status}</small></span><ArrowUpRight size={15}/></button>)}<div className="eyebrow">TASKS</div>{w?.tasks.filter(t => t.title.toLowerCase().includes(search.toLowerCase())).slice(0, 6).map(t => <button key={t.id} onClick={() => { setSearchOpen(false); setTaskModal(t); }}><Circle size={17}/><span>{t.title}<small>{w.projects.find(p => p.id === t.projectId)?.name}</small></span><StatusBadge status={t.status}/></button>)}{w && !w.projects.some(p => p.name.toLowerCase().includes(search.toLowerCase())) && !w.tasks.some(t => t.title.toLowerCase().includes(search.toLowerCase())) && <div className="small-empty">Nothing here yet. Try a different search.</div>}</div><div className="search-footer"><Command size={13}/> K to search from anywhere<span>Make a little space for clarity.</span></div></Modal>}
  {toast && <div className={`toast ${toast.error ? "toast-error" : ""}`} role={toast.error ? "alert" : "status"}>{toast.error ? <AlertCircle size={19}/> : <CircleCheck size={19}/>}<span>{toast.message}</span><button aria-label="Dismiss notification" onClick={() => setToast(null)}><X size={16}/></button></div>}
  </div>;
}
const memoryFilesCount = 7;
